### ISSUE TITLE
Could not install java code after git clone in _clone.sh

### ISSUE THREAD

**Issue by gribok** [uhafner/warnings-ng-plugin-devenv#5]
I am trying to setup the dev environment for warnings-ng-plugin and got some trouble at **installation step 1**.
Git clone worked well inside the clone script, but I got an error message during the build phase of the packages

Run commands in following order:
1. `$ git clone https://github.com/uhafner/warnings-ng-plugin-deven.git`
2. `$ cd warnings-ng-plugin-deven`
3. `$  bash clone-repos-https.sh`

```
Clone of Jenkins plugins using HTTPS
Press any key to continue...

[...SKIPPING LOG OF GIT CLONE...]

Done cloning. Note that you need to change the remotes for each
of the repositories you want to contribute to.
Press any key to compile the projects...
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.8.0_242, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.184-linuxkit", arch: "amd64", family: "unix"
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[ERROR] Internal error: java.lang.ArrayIndexOutOfBoundsException: 31759 -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.ArrayIndexOutOfBoundsException: 31759
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:168)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 31759
        at org.codehaus.plexus.util.xml.pull.MXParser.parsePI(MXParser.java:2470)
        at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1257)
        at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1105)
        at org.codehaus.plexus.util.xml.pull.MXParser.nextTag(MXParser.java:1090)
        at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.parsePluginExecution(MavenXpp3ReaderEx.java:3541)
        at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.parsePlugin(MavenXpp3ReaderEx.java:3336)
        at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.parseBuildBase(MavenXpp3ReaderEx.java:1398)
        at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.parseProfile(MavenXpp3ReaderEx.java:3751)
        at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.parseModel(MavenXpp3ReaderEx.java:2809)
        at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.read(MavenXpp3ReaderEx.java:4627)
        at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.read(MavenXpp3ReaderEx.java:837)
        at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:118)
        at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:91)
        at org.apache.maven.model.building.DefaultModelProcessor.read(DefaultModelProcessor.java:77)
        at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:456)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:261)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:232)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:410)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:379)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:495)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:379)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:343)
        at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
        at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        ... 11 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

**Java Version**:
`$ java -version`
```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```

**Operation System**
CentOS Linux release 7.6.1810 (Core) 

**Maven Version**
`mvn --version`
```
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.8.0_242, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.184-linuxkit", arch: "amd64", family: "unix"
```

The `~/.m2/repository/` is empty.

Does exist some advice to fix it?

Thanks.

**Comment by uhafner** [comment]
I see. I never tried to build with such an old maven version. Can you please upgrade maven and retry? Current version is 3.6.3.

**Comment by gribok** [comment]
I have upgraded maven to version 3.6.3 and tried `mvn -V -U -e install -DskipTests` from `_clone.sh` again.

`mvn --version`
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/maven
Java version: 1.8.0_242, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.184-linuxkit", arch: "amd64", family: "unix"
```

After re-run, I was facing new issue with gpg-plugin
`Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign`.

I fixed it with skipping of gpg-checking
`mvn -V -U -e install -DskipTests  -Dgpg.skip=true`

Now, it works. Thanks for the support.
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Java coding style 0.4.2-SNAPSHOT ................... SUCCESS [01:29 min]
[INFO] Static Analysis Model and Parsers 8.0.0-beta8-SNAPSHOT SUCCESS [01:54 min]
[INFO] Analysis Model API Plug-in 8.0.0-beta8-SNAPSHOT .... SUCCESS [04:09 min]
[INFO] Forensics API Plugin 0.7.0-beta7-SNAPSHOT .......... SUCCESS [03:24 min]
[INFO] Git Forensics Plugin 0.7.0-beta5-SNAPSHOT .......... SUCCESS [02:04 min]
[INFO] Warnings Next Generation Plugin 8.0.0-beta6-SNAPSHOT SUCCESS [07:51 min]
[INFO] Acceptance Test Harness 1.70-SNAPSHOT .............. SUCCESS [04:12 min]
[INFO] Warnings Next Generation Plugin development environment 1.0.0-SNAPSHOT SUCCESS [  1.700 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25:14 min
[INFO] Finished at: 2020-02-12T10:22:06Z
[INFO] ------------------------------------------------------------------------
```

**Comment by uhafner** [comment]
Thanks for reporting, I removed GPG signing from the default profile in https://github.com/uhafner/codingstyle/commit/315ce5d07df1cc2319262eb1050823197b38762f
